heereal/Bunyang_MoeumZip

src/components/MainPage/HomeList/HomeList.tsx, src/pages/admin/nemo042116.tsx, src/pages/index.tsx
Main Page firebase DB 데이터 적용한 게 dev에 안 들어가서 다시 PR
- Main Page에 firebase DB 데이터 적용 및 주석 삭제 
없습니다.
=> [edit] Main Page firebase DB 데이터 적용

src/components/GlobalComponents/CategoryBar/CategoryBar.tsx, src/components/GlobalComponents/CategoryBar/style.tsx, src/components/GlobalComponents/InfoLink/InfoLink.tsx, src/components/GlobalComponents/InfoLink/style.tsx
`서브네브바에 청약경쟁률/당첨자를 확인할 수 있게 링크를 걸어둠 `
`Next.JS/Link 활용  했으나 스타일컴포넌트는 적용이 안됨`
=> [feat] 청약경쟁률 /당첨자 확인 버튼 구현

src/components/GlobalComponents/MapSection/MapSection.tsx, src/hooks/useMap.ts, src/pages/_app.tsx, src/pages/admin/nemo042116.tsx, src/pages/calendar/index.tsx
- 좌표 못찾은 것들 친절하게 안내하는 기능 구현
- nemo042116.tsx : 177 /  조건문에서 else를 추가함
=> [feat] 좌표 못찾은 것들 친절하게 안내하는 기능 구현

next.config.js, src/common/api.ts, src/components/DetailPage/PostDetail/PostDetail.tsx, src/components/GlobalComponents/LoadingSpinner/LoadingSpinner.tsx, src/hooks/index.ts, src/hooks/useBookmark.tsx, src/pages/loading/index.tsx, src/pages/my/index.tsx
- 북마크 추가 기능 및  마이페이지에서 북마크 목록을 불러오도록 구현했습니다.
- 전체적인 리팩토링을 진행했습니다.
- 카카오로 소셜 로그인 시 프로필 이미지 링크 출처를 허용할 수 없었던 문제를 해결했습니다. (next.config.js 수정)
- 디테일 페이지에 북마크 버튼 추가 및 북마크 개수를 카운트하는 부분을 추가했습니다.
- 북마크 버튼 클릭 시 로그인 여부에 따라 유효성 검사를 진행합니다.
- 북마크 버튼 클릭 시 유저 정보에 따라 북마크 추가 혹은 삭제가 가능합니다.
- 마이페이지에 내가 북마크한 분양 정보 목록을 불러오도록 구현했습니다.
- PostDatail  컴포넌트를 전체적으로 리팩토링하며 useBookmark라는 커스텀 훅을 생성했습니다.
-  loading 페이지에서 LoadingSpinner 컴포넌트를 분리했습니다. (로딩페이지 보여줄 때 사용하세요!😇)
없습니다.
=> [feat] 북마크 기능 및 마이페이지에 내가 북마크한 목록 불러오기 구현

src/components/DetailPage/PostDetail/PostDetail.tsx, src/pages/signup/index.tsx
- 디테일 페이지에서 마커 이동 시 북마크도 바로 업데이트되도록 수정했습니다.
- PostDetail 컴포넌트에 북마크 데이터 refetch를 추가했습니다.
없어요.
=> [edit] 디테일 페이지에서 마커 이동 시 북마크가 바로 업데이트되도록 수정

src/common/api.ts, src/components/DetailPage/PostDetail/PostDetail.tsx, src/hooks/useBookmark.tsx
- 디테일 페이지에서 마커 이동 시 북마크가 바로 업데이트되도록 수정했습니다.
- 디테일 페이지 getBookmarkList 파라미터를 postId로 변경한 후 useEffect에 bookmarksListRefetch 함수 실행을 추가했습니다.
없어요.
=> [edit] 디테일 페이지 getBookmarkList 파라미터 변경-실시간 업데이트 반영

src/components/DetailPage/Comments/AddComment.tsx, src/components/DetailPage/Comments/EditComment.tsx, src/components/GlobalComponents/Search/Search.tsx, src/components/MainPage/CountTabs.tsx, src/hooks/useBookmark.tsx, src/pages/admin/nemo042116.tsx, src/pages/my/index.tsx, src/pages/signup/index.tsx
카테고리 선택 리스트 수정 및 AlertUI 모두 적용
- 카테고리 선택했을 때 해당 데이터가 없으면 0으로 뜨는 게 아니라 유저리스트 혹은 전체리스트가 뜨는 문제 수정했습니다. 
- AlertUI 모두 적용
- Alert 뜰 때 width가 살짝 밀리는 문제 해결해야 합니다.  
`없습니다.`
=> [edit] 카테고리 선택 리스트 수정

src/components/GlobalComponents/AlertUI/AlertUI.tsx, src/components/GlobalComponents/AlertUI/style.tsx, src/components/GlobalComponents/Search/Search.tsx, src/pages/admin/nemo042116.tsx, src/styles/admin.style.tsx, src/styles/search.style.tsx
- 오류 메시지
- The tag <text> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
at text
- <text>를 사용할 수 없다는 오류가 발생해서 text tag -> p tag로 교체
- next.js에서 제공하는 `<Text>`태그를 사용해야 하는데 style component 안에서 text tag를 사용해서 오류가 났습니다. 
-  text tag -> p tag 교체
`없습니다.`
=> [edit] 스타일 컴포넌트 text tag -> p tag로 교체

src/components/GlobalComponents/Header/style.tsx, src/components/GlobalComponents/SearchInput/style.tsx, src/components/MainPage/CategoryBar/style.tsx
- 화면 크기에 따라 필터 위치 바뀌는 것 수정
- position relative와 absolute 적절히 활용해 화면 크기에 따라 카테고리 필터 위치가 바뀌는 부분 수정했습니다.
- 검색 버튼도 위치 바뀌는 것 수정했으나 인풋창 부분이 화면 크기가 달라져도 postion fixed처럼 움직이지 않아서 수정이 필요합니다. 
- 청약 정보 확인 버튼 Link 안에 있는 a태그는 style component를 쓸 수 없어 다시 a태그로 돌려놨더니 링크 이동 잘 됩니다.
- 로고 부분 와이어프레임과 동일하게 만들고 홈버튼 연결 안 한 부분 수정했습니다.
=> [design] 화면 크기에 따라 필터 위치 바뀌는 것 수정

src/components/DetailPage/PostDetail/PostDetail.tsx, src/components/GlobalComponents/MapSection/MapSection.tsx
-지도 에러 해결
-Mapsection.tsx:170에 의존성 배열로 router 를 추가함
=> [fix] 지도 에러 해결 

src/pages/signup/index.tsx
- 회원가입 시 관심 카테고리 선택 안되는 문제를 해결했습니다.
- 회원가입 페이지에서 카테고리가 전체 선택된 것으로 보여주고, 카테고리 선택이 가능하도록 수정했습니다.
없습니다.
=> [edit] 회원가입 시 관심 카테고리 선택 안되는 문제 해결

src/pages/admin/nemo042116.tsx
-  merge 과정에서 에러 해결했습니다.
-  merge 과정에서 에러 해결했습니다.
=> [edit] merge 과정에서 에러 해결

src/components/DetailPage/PostDetail/DetailHeader.tsx
- 상세 페이지 안 들어가지는 오류 해결
- 상세 페이지 session뒤 optional chaining 추가
-  `${session?.user.provider}_${session?.user.email}`
=> [fix]상세 페이지 optional chaining 추가

src/components/DetailPage/PostDetail/PostDetail.tsx, src/components/GlobalComponents/Header/style.tsx, src/components/GlobalComponents/Maps/Cluster/ClusterLarge.tsx, src/components/GlobalComponents/Maps/MarkerIcon.tsx, src/components/GlobalComponents/Maps/Markers.tsx, src/components/GlobalComponents/Maps/Overlay.tsx, src/components/GlobalComponents/Maps/style.tsx, src/pages/_app.tsx, src/pages/detail/[postid].tsx, src/pages/search/[keyword].tsx, src/store/selectors.ts
=> [design] 지도 css완성

src/components/GlobalComponents/Maps/Markers.tsx
- 마커아이콘 418 오류 해결
- 마커아이콘 418 오류 해결
=> [edit] 418 오류고침

src/components/GlobalComponents/Maps/Markers.tsx, src/pages/search/[keyword].tsx
=> [edit] 에러해결

src/components/GlobalComponents/Header/Header.tsx, src/components/GlobalComponents/Header/style.tsx, src/components/GlobalComponents/HomeList/style.tsx, src/components/GlobalComponents/SearchInput/SearchInput.tsx, src/components/GlobalComponents/SearchInput/style.tsx, src/components/MainPage/CategoryBar/style.tsx, src/components/MainPage/CountTabs/CountTabs.tsx, src/components/MainPage/CountTabs/style.tsx, src/components/MainPage/InfoLinkBtn/style.tsx
-폰트 수정 및 헤더 언더라인 추가
-폰트 수정 및 헤더 언더라인 추가
=> [design]  폰트 수정 및 헤더 언더라인 추가

src/common/utils.tsx, src/components/DetailPage/Comments/AddComment.tsx, src/components/DetailPage/Comments/AddReply.tsx, src/components/DetailPage/Comments/EditComment.tsx, src/components/DetailPage/Comments/Replies.tsx, src/components/GlobalComponents/AlertUI/AlertUI.tsx, src/components/GlobalComponents/AlertUI/style.tsx, src/components/GlobalComponents/Header/Header.tsx, src/components/GlobalComponents/HomeList/HomeList.tsx, src/components/GlobalComponents/SearchInput/SearchInput.tsx, src/components/MainPage/CountTabs/CountTabs.tsx, src/components/MyPage/EditProfile/EditProfile.tsx, src/components/MyPage/EditProfileModal/EditProfileModal.tsx, src/components/MyPage/MyTabs/MyTabs.tsx, src/hooks/index.ts, src/hooks/index.tsx, src/hooks/useBookmark.tsx, src/pages/signup/index.tsx
- Alert UI 디자인 적용
-  Alert UI 디자인 적용 및 페이지별 모두 적용
- today 함수 쓰는 useHomeList hook을 useEffect에서 실행되게 코드 수정
=> [design] Alert UI 디자인 적용

src/components/GlobalComponents/HomeList/HomeList.tsx, src/components/GlobalComponents/HomeList/style.tsx, src/components/GlobalComponents/SelectMyRegion/SelectMyRegion.tsx, src/components/GlobalComponents/SelectMyRegion/style.tsx, src/components/GlobalComponents/SelectMyTypes/SelectMyTypes.tsx, src/components/MainPage/CountTabs/CountTabs.tsx, src/components/MainPage/CountTabs/style.tsx, src/components/MyPage/MyTabs/MyTabs.tsx, src/components/MyPage/MyTabs/style.tsx, src/pages/search/[keyword].tsx, types/type.d.ts
- 디자이너님 피드백을 반영하여 마이페이지 CSS를 추가적으로 수정했습니다.
- 웹 및 반응형 모두 수정했습니다.
=> [design] 마이페이지 CSS 추가 수정

package-lock.json, src/components/GlobalComponents/LoadingSpinner/LoadingSpinner.tsx, src/components/GlobalComponents/SelectMyRegion/style.tsx, src/components/MyPage/EditProfileModal/EditProfileModal.tsx, src/pages/loading/index.tsx, src/styles/claendar.style.tsx
=> [design] 청약캘린더 미디어 쿼리 추가 수정

package-lock.json, seo.config.js, src/components/DetailPage/PostDetail/style.tsx, src/components/GlobalComponents/Maps/Cluster/ClusterLarge.tsx, src/components/GlobalComponents/Maps/Cluster/ClusterMid.tsx, src/components/GlobalComponents/Maps/Cluster/ClusterSmall.tsx, src/components/GlobalComponents/Maps/Map.tsx
##개요
-상세페이지 헤더 변경
##작업사항
-상세페이지 헤더 변경
=> [design] 상세페이지 헤더 변경

seo.config.js, src/common/firebase.ts, src/components/GlobalComponents/AlertUI/style.tsx, src/components/GlobalComponents/HamburgerModal/HamburgerModal.tsx, src/components/GlobalComponents/HamburgerModal/style.tsx, src/components/GlobalComponents/Header/Header.tsx, src/components/GlobalComponents/TopBtn/TopBtn.tsx, src/components/GlobalComponents/TopBtn/style.tsx, src/components/MainPage/CategoryBar/style.tsx, src/components/MainPage/InfoLinkBtn/InfoLinkBtn.tsx, src/pages/admin/nemo042116.tsx, src/pages/calendar/index.tsx, src/pages/index.tsx, src/pages/search/[keyword].tsx
- 햄버거 모달 수정
- top버튼 반응형 적용
- 외부 링크 새 창에서 열리게 수정
- 필터 너비 수정
- alertUI 반응형 적용 
- 햄버거 모달 위치 수정해서 헤더 위에 보이게 했습니다. 
- 청약 당첨률 확인 등 외부링크는 새 창에서 열리게 수정했습니다.
- 사용하지 않는 firebase auth 삭제했습니다. 
- 지역 및 분양 형태 필터 모바일에서 너비 수정
- top버튼 반응형 수정 및 페이지별 적용 완료
- 반응형 top 버튼 컴포넌트 삭제 후 top버튼 컴포넌트로 합쳐 중복 제거 
- alertUI 반응형 - 모바일 크기에 맞게 박스 크기, 폰트 수정
- og image 수정
=> [edit]햄버거 모달 수정, Top버튼 반응형 적용 

seo.config.js
##개요 
오지이미지 수정
##작업사항 
오지이미지 수정
=> [edit] 오지이미지 수정

seo.config.js, src/pages/loading/index.tsx
=> [Edit] 로딩 페이지 코드 수정

seo.config.js
=> [edit] 오지 이미지 5차 수정

src/components/GlobalComponents/HamburgerModal/HamburgerModal.tsx, src/components/GlobalComponents/HamburgerModal/style.tsx, src/components/GlobalComponents/Header/Header.tsx, src/components/GlobalComponents/Header/SearchHeader/SearchMobile.tsx, src/components/GlobalComponents/Header/SearchHeader/style.tsx, src/components/GlobalComponents/Header/style.tsx, src/components/GlobalComponents/HomeList/style.tsx, src/components/GlobalComponents/NoResult/NoResult.tsx, src/components/GlobalComponents/NoResult/style.tsx, src/components/MainPage/CategoryBar/CategoryBar.tsx, src/components/MainPage/CategoryBar/style.tsx, src/pages/404.tsx, src/styles/globals.css
- 디자인 회의 후 수정 사항 반영
- 반응형 검색창 애니메이션 추가
- 지역 및 분양형태 필터 간격, 너비 위치 조절
- 로고 폰트 Regular로 변경
- 404 페이지 반응형 작업
- 반응형 검색창 애니메이션 추가
=> [design] 디자인 회의 후 수정 사항 반영 및 반응형 검색창 애니메이션 추가

src/components/DetailPage/PostDetail/DetailHeader.tsx, src/components/DetailPage/PostDetail/SubscriptionSchedule.tsx, src/components/DetailPage/PostDetail/SupplyInfo.tsx, src/components/DetailPage/PostDetail/style.tsx, src/components/MainPage/CountTabs/CountTabs.tsx, src/components/MainPage/CountTabs/style.tsx, src/pages/index.tsx, src/styles/main.style.tsx
=> [design] 디자인 회의 결과 반영

src/components/GlobalComponents/Layout/style.tsx, src/components/GlobalComponents/Maps/Map.tsx, src/components/GlobalComponents/Maps/style.tsx, src/components/MainPage/CategoryBar/CategoryBar.tsx, src/components/MainPage/CategoryBar/style.tsx, src/components/MainPage/CountTabs/CountTabs.tsx, src/pages/index.tsx, src/store/selectors.ts, src/styles/main.style.tsx, types/type.d.ts
=> [design] 메인페이지 반응형 수정

src/components/GlobalComponents/Header/Header.tsx, src/components/GlobalComponents/Maps/style.tsx, src/styles/main.style.tsx
개요
- 메인 브라우저 스크롤 안 되게 수정
- 작업사항
- 메인 브라우저 스크롤 안 되게 수정
=> [design] 메인 브라우저 스크롤 안 되게 수정

src/components/GlobalComponents/Maps/MapSection.tsx, src/components/GlobalComponents/Maps/style.tsx, src/styles/main.style.tsx
=> [design]  메인페이지 반응형

src/components/DetailPage/Comments/CommentsList.tsx, src/components/DetailPage/Comments/style.tsx, src/components/DetailPage/PostDetail/DetailHeader.tsx, src/components/GlobalComponents/Header/SearchHeader/style.tsx, src/components/GlobalComponents/Header/style.tsx, src/components/MainPage/CategoryBar/style.tsx, src/components/MyPage/EditProfileModal/EditProfileModal.tsx, src/components/MyPage/EditProfileModal/style.tsx
- 디자인 수정 사항 반영
- 헤더 검색아이콘-햄버거 사이 간격 더 넓히기
- 분양형태 필터 버튼 및 전체 박스 height 늘리기
- 프로필 수정 닉네임 인풋&버튼 크기 늘리기
- 상세페이지 북마크 별모양 똑같이 통일(이미지에서 아이콘으로 대체)
- 마지막 댓글 밑에 여백 주기
- 프로필 수정 닉네임 인풋창&버튼 크기 및 폰트 사이즈 키우기
=> [design] 디자인 수정 사항 반영

src/components/GlobalComponents/SelectMyRegion/SelectMyRegion.tsx, src/components/GlobalComponents/SelectMyRegion/style.tsx, src/components/GlobalComponents/SelectMyTypes/SelectMyTypes.tsx, src/components/MainPage/CategoryBar/style.tsx, src/components/MainPage/CountTabs/style.tsx, src/components/MainPage/InfoLinkBtn/style.tsx, src/components/MyPage/MyTabs/MyTabs.tsx, src/components/MyPage/MyTabs/style.tsx, src/pages/signup/index.tsx, types/type.d.ts
- 사용자 피드백과 디자이너 피드백을 반영하여 수정하였습니다.
- 메인 페이지 CountTab의 높이를 조정했습니다.
- 메인페이지에 관심 카테고리 버튼의 텍스트가 두 줄이 되는 문제를 수정했습니다.
- 마이페이지 북마크 탭에 북마크가 없을 때 화면을 가운데 정렬로 수정했습니다.
- 회원가입 시 관심 카테고리 기본값을 아무것도 선택되지 않은 것으로 변경했습니다.
=> [edit] 회원가입 관심 카테고리 기본값 및 전반적인 CSS 수정

src/components/DetailPage/PostDetail/DetailKeyInfo.tsx, src/components/DetailPage/PostDetail/ExtraInfo.tsx, src/components/DetailPage/PostDetail/LHDetail.tsx, src/components/DetailPage/PostDetail/SpecialSupply.tsx, src/components/DetailPage/PostDetail/SubscriptionSchedule.tsx, src/components/DetailPage/PostDetail/SupplyInfo.tsx, src/components/DetailPage/PostDetail/style.tsx
#개요
- 상세 페이지 테이블로 모두 변경 및 유의 사항 줄 간격 추가
#작업사항
- 상세 페이지 div로 되어있던 표 모두 테이블로 변경 및 유의 사항 줄 간격 추가
=> [design] 상세 페이지 테이블로 모두 변경 및 유의 사항 줄 간격 추가

src/components/MyPage/MyTabs/MyTabs.tsx, src/components/MyPage/MyTabs/style.tsx
- 북마크 BookmarkListContainer의 justifyContent 속성에 조건문을 추가했습니다.
=> [design] 마이페이지 북마크탭 CSS 정렬 수정

next-sitemap.config.js, package-lock.json, package.json, public/robots.txt, public/sitemap-0.xml, public/sitemap.xml, seo.config.ts, src/components/DetailPage/PostDetail/PostDetail.tsx, src/pages/404.tsx, src/pages/_app.tsx, src/pages/admin/nemo042116.tsx, src/pages/calendar/index.tsx, src/pages/index.tsx, src/pages/loading/index.tsx, src/pages/my/index.tsx, src/pages/search/[keyword].tsx, src/pages/signup/index.tsx
- 구글, 네이버 SearchAdvisor 등록을 위해 설정을 추가했습니다.
- 구글. 네이버 script 태그를 추가했습니다.
- next-sitemap  라이브러리를 이용하여 robots.txt, sitemap.xml 파일을 생성했습니다.
- next-sitemap 설치
=> [feat] 구글, 네이버 SearchAdvisor 등록위한 설정 추가

src/components/MainPage/CountTabs/CountTabs.tsx, src/pages/detail/[postid].tsx, src/pages/index.tsx, src/pages/loading/index.tsx, src/styles/detail.style.tsx, src/styles/main.style.tsx
- 메인페이지 -> 상세페이지 이동시 로딩 스피너 돌게 했음
- router.events 를 추가함
=> [edit] 메인페이지 -> 상세페이지 이동시 로딩 스피너 돌게 했음

src/components/GlobalComponents/Header/SearchHeader/SearchInput.tsx, src/components/MainPage/CategoryBar/CategoryBar.tsx, src/components/MainPage/CountTabs/CountTabs.tsx, src/components/MyPage/MyTabs/MyTabs.tsx, src/pages/detail/[postid].tsx, src/pages/index.tsx, src/pages/loading/index.tsx, src/pages/search/[keyword].tsx
- dynamic 코드 위치 변경
- 검색placeholder 수정
- 필터 새로 고침 완벽 구현
- dynamic 코드 위치를 컴포넌트 안에서 컴포넌트 밖, import 바로 아래로 변경
- 검색placeholder 수정. 분양 정보를 검색해보세요 -> 지역, 분양형태, 주택명을 검색해보세요.
- 필터 새로 고침 시 유지 수정 -> 로그인을 했을 때도 필터 변경 후 새로고침 시 필터가 유지되며 유저가 마이페이지에서 관심 필터를 변경하면 변경한 필터가 메인 페이지에 바로 반영됩니다.
=> [edit] dynamic 코드 위치 변경, 검색placeholder 수정, 필터 새로 고침 완벽 구현

src/components/GlobalComponents/Header/SearchHeader/SearchInput.tsx, src/components/MainPage/CategoryBar/CategoryBar.tsx, src/components/MainPage/CountTabs/CountTabs.tsx, src/components/MyPage/MyTabs/MyTabs.tsx, src/pages/detail/[postid].tsx, src/pages/index.tsx, src/pages/loading/index.tsx, src/pages/search/[keyword].tsx
=> [edit] 재배포

next.config.js, src/components/DetailPage/PostDetail/PostDetail.tsx, src/pages/calendar/index.tsx, src/pages/my/index.tsx
- OG 태그 및 아파트 매매 실거래가 API 코드 수정
=> [edit] OG 태그 및 아파트 매매 실거래가 API 코드 수정

next.config.js
=> [edit] next.config.js rewrites 수정
